# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc1eeebbaaaab48dc676e468ab56ce8543fd14daa8d3eb1e0a841b2107450669c3fd2193d1db8d0dbd43c475cb4371b1459fb793cc6b07764861ed6980c03c36

test:
  secret_key_base: 5bfd49a9915443de2cfc51dbfbd4bb2001158384d0d6b981063ef108ff9a51a63f4de57a1cfc3f1a7a9ceb88840962d074d58963e9e022d48218520673e29fe6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
